backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images/featured" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/featured" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "songs" # Used in routes, e.g., /admin/collections/songs
    label: "Songs" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}

      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}